export const menuData = [
  {
    id: 1,
    title: "صفحه اصلی",
    link: "/dashboard/home",
    menueKey: "home",
    icon: "/images/svg/home.svg",
  },
  {
    id: 2,
    title: "مسکن",
    link: "/dashboard/housing",
    menueKey: "housing",
    icon: "/images/svg/building.svg",
  },
  {
    id: 3,
    title: "خودرو",
    link: "/dashboard/car",
    menueKey: "car",
    icon: "/images/svg/car.svg",
  },
  {
    id: 4,
    title: "ارز و ارز دیجیتال",
    link: "/dashboard/currency",
    menueKey: "currency",
    icon: "/images/svg/currency.svg",
  },

  {
    id: 5,
    title: "سکه و طلا",
    link: "/dashboard/gold",
    menueKey: "gold",
    icon: "/images/svg/gold.svg",
  },
  // {
  //   id: 6,
  //   title: "لوازم خانگی",
  //   link: "/dashboard/household-appliances",
  //   menueKey: "household-appliances",
  //   icon: "/images/svg/home.svg",
  // },
  {
    id: 7,
    title: "اخبار",
    link: "/dashboard/news",
    menueKey: "news",
    icon: "/images/svg/news.svg",
  },
  {
    id: 8,
    title: "شبکه‌های اجتماعی",
    link: "/dashboard/social-media",
    menueKey: "social-media",
    icon: "/images/svg/social.svg",
  },
  {
    id: 9,
    title: "کسب‌و‌کار",
    link: "/dashboard/business",
    menueKey: "business",
    icon: "/images/svg/jobs.svg",
  },
  {
    id: 10,
    title: "پروفایل",
    link: "/dashboard/profile",
    menueKey: "profile",
    icon: "/images/svg/user.svg",
  },
];
